# Jekyll configuration for GitHub Pages
title: Joshua Passmore
description: PhD student in pure mathematics and TA at the African Institute for Mathematical Sciences (AIMS) South Africa
author: Joshua Passmore
email: josh@aims.ac.za
url: https://joshuapassmore.github.io
baseurl: ""

# Theme
theme: minima

# Plugins
plugins:
  - jekyll-feed
  - jekyll-seo-tag

# Markdown processor
markdown: kramdown
